# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RIAL_3_2021_4(object):
    def setupUi(self, RIAL_3_2021_4):
        RIAL_3_2021_4.setObjectName("RIAL_3_2021_4")
        RIAL_3_2021_4.resize(1080, 888)
        RIAL_3_2021_4.setStyleSheet("background-color: rgb(181, 223, 255)")
        self.graphicsView = QtWidgets.QGraphicsView(RIAL_3_2021_4)
        self.graphicsView.setGeometry(QtCore.QRect(550, 130, 511, 311))
        self.graphicsView.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(RIAL_3_2021_4)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 130, 511, 311))
        self.graphicsView_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.pushButton = QtWidgets.QPushButton(RIAL_3_2021_4)
        self.pushButton.setGeometry(QtCore.QRect(210, 450, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(255, 167, 220)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(RIAL_3_2021_4)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 450, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 167, 220)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(RIAL_3_2021_4)
        self.label.setGeometry(QtCore.QRect(360, 40, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView_3 = QtWidgets.QGraphicsView(RIAL_3_2021_4)
        self.graphicsView_3.setGeometry(QtCore.QRect(280, 490, 511, 311))
        self.graphicsView_3.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.pushButton_3 = QtWidgets.QPushButton(RIAL_3_2021_4)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 820, 93, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 167, 220)")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(RIAL_3_2021_4)
        QtCore.QMetaObject.connectSlotsByName(RIAL_3_2021_4)

    def retranslateUi(self, RIAL_3_2021_4):
        _translate = QtCore.QCoreApplication.translate
        RIAL_3_2021_4.setWindowTitle(_translate("RIAL_3_2021_4", "Dialog"))
        self.pushButton.setText(_translate("RIAL_3_2021_4", "Arm View"))
        self.pushButton_2.setText(_translate("RIAL_3_2021_4", "All View"))
        self.label.setText(_translate("RIAL_3_2021_4", "Video Streaming"))
        self.pushButton_3.setText(_translate("RIAL_3_2021_4", "LVDAC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RIAL_3_2021_4 = QtWidgets.QDialog()
    ui = Ui_RIAL_3_2021_4()
    ui.setupUi(RIAL_3_2021_4)
    RIAL_3_2021_4.show()
    sys.exit(app.exec_())
